name: build-release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setting up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'temurin'
      - name: Build wit Ant
        run: ant -noinput -buildfile build.xml
      - name: Uploading jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: out/artifacts/jar/LoggerLibrary.jar